###############################
# input_datetime - So the time report automation fires can be set in the UI
###############################
input_datetime:
  morning_report:
    name: Morning Report
    has_date: false
    has_time: true
  audible_notification_on:
    name: Audible Notifications On
    has_date: false
    has_time: true
  audible_notification_off:
    name: Audible Notifications Off
    has_date: false
    has_time: true

automation:
  - id: 81bee5ee-6820-4626-aebf-3deb8de69e4d
    alias: Turn On Audible Notifications
    initial_state: true
    trigger:
      platform: time
      at: input_datetime.audible_notification_on
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.audible_notifications

  # Turn off audible notifications if they have't been turned off yet.
  - id: e0e9c774-6abe-42aa-bdab-32108bebb0e9
    alias: Turn Off Audible Notifications
    initial_state: true
    trigger:
      - platform: time
        at: input_datetime.audible_notification_off
    condition:
      - condition: state
        entity_id: input_boolean.audible_notifications
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.audible_notifications
