binary_sensor:
  - platform: group
    name: "Back Stairs Occupancy"
    device_class: motion
    entities:
      - binary_sensor.back_stairs_motion
      - binary_sensor.back_door_contact_sensor

# ----------------------------------------------------------
# ----------------------------------------------------------

input_boolean:
  disable_back_stairs_motion_automation:
    name: Disable Back Stairs Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false

# ----------------------------------------------------------
# ----------------------------------------------------------

automation:
  # ----------------------------------------------------------
  - id: turn_on_back_stairs_lights_when_occupancy_detected
    alias: Turn ON back stairs lights when occupancy detected
    trigger:
      - platform: state
        entity_id: binary_sensor.back_stairs_occupancy
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: switch.back_foyer_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_back_stairs_motion_automation
        state: 'off'
      # use the kitchen LUX
      - condition: numeric_state
        entity_id: sensor.kitchen_p1_illuminance
        below: 100
    action:
      - service: switch.turn_on
        entity_id: switch.back_foyer_lights
    mode: single
  # ----------------------------------------------------------
  - id: turn_off_back_stairs_lights_when_occupancy_cleared
    alias: Turn OFF back stairs lights when occupancy cleared
    trigger:
      - platform: state
        entity_id: binary_sensor.back_stairs_occupancy
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 0
          seconds: 30
    condition:
      - condition: state
        entity_id: binary_sensor.back_stairs_occupancy
        state: 'off'
      - condition: state
        entity_id: switch.back_foyer_lights
        state: 'on'
      - condition: state
        entity_id: input_boolean.disable_back_stairs_motion_automation
        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.back_foyer_lights
    mode: single
  # ----------------------------------------------------------
  - id: disable_back_light_automation_at_night
    alias: Stop blinding the person at the bottom stairs
    trigger:
      - platform: time
        at: "22:30:00"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.disable_back_stairs_motion_automation
  # ----------------------------------------------------------
  - id: enable_back_light_automation_at_night
    alias: Enable the back stairs lights automation in the morning
    trigger:
      - platform: time
        at: "06:00:00"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.disable_back_stairs_motion_automation