binary_sensor:
  - platform: group
    name: "Denver Bedroom Occupancy"
    device_class: motion
    entities:
      - binary_sensor.denver_room_motion_pir

# ----------------------------------------------------------
# ----------------------------------------------------------

input_boolean:
  disable_denver_bedroom_motion_automation:
    name: Disable Denver Bedroom Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false

# ----------------------------------------------------------
# ----------------------------------------------------------

automation:
  # ----------------------------------------------------------
  # - id: turn_on_denver_bedroom_lights_when_occupancy_detected
  #   alias: Turn ON Denver Bedroom lights when occupancy detected
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.denver_bedroom_occupancy
  #       from: 'off'
  #       to: 'on'
  #   condition:
  #     - condition: state
  #       entity_id: light.denver_light
  #       state: 'off'
  #     - condition: state
  #       entity_id: input_boolean.guest_mode
  #       state: 'off'
  #     - contidition: state
  #       entity_id: input_boolean.disable_denver_bedroom_motion_automation
  #       state: 'off'
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.denver_light
  #   mode: single
  # ----------------------------------------------------------
  - id: notify_denver_his_lights are about to turn off
    alias: Notify Denver his lights are about to turn off
    trigger:
      - platform: state
        entity_id: binary_sensor.denver_bedroom_occupancy
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 8 # do not use default, Denver does allot of sedetary stuff //"{{ states('input_number.light_timeout') | int }}"
          seconds: 0
    condition:
      - condition: state
        entity_id: binary_sensor.denver_bedroom_occupancy
        state: 'off'
      - condition: state
        entity_id: light.denver_light
        state: 'on'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_denver_bedroom_motion_automation
        state: 'off'
    action:
      - service: script.text_notify
        data_template:
          who: "denver"
          message: >-
            Your lights are still on, but I don't detect you in your room, either you aren't there, or more around more - I will turn your lights off in 2 minutes!

  # ----------------------------------------------------------
  - id: turn_off_denver_bedroom_lights_when_occupancy_cleared
    alias: Turn OFF Denver's Bedroom lights when occupancy cleared
    trigger:
      - platform: state
        entity_id: binary_sensor.denver_bedroom_occupancy
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 10 # do not use default, Denver does allot of sedetary stuff //"{{ states('input_number.light_timeout') | int }}"
          seconds: 0
    condition:
      - condition: state
        entity_id: binary_sensor.denver_bedroom_occupancy
        state: 'off'
      - condition: state
        entity_id: light.denver_light
        state: 'on'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_denver_bedroom_motion_automation
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.denver_light
      - service: script.text_notify
        data_template:
          who: "denver"
          message: >-
            I warned ya - lights are now off.  Good day.
      
    mode: single

# ----------------------------------------------------------
# ----------------------------------------------------------