binary_sensor:
  - platform: group
    name: "Family Room Occupancy"
    device_class: motion
    entities:
      - binary_sensor.family_room_p1_motion
      - binary_sensor.family_room_secondary_pir
      - binary_sensor.theatre_mode

# ----------------------------------------------------------
# ----------------------------------------------------------

input_boolean:
  disable_family_room_motion_automation:
    name: Disable Family Room Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false

# ----------------------------------------------------------
# ----------------------------------------------------------

group:
  family_room_reading_lights:
    name: Reading Lights
    icon: mdi:book-open-page-variant-outline
    entities:
      - light.reading_lights_left
      - light.reading_lights_right

template:
  - binary_sensor:
      - name: "Theatre Mode"
        icon: mdi:television
        state: >
          {{ is_state('remote.58_hisense_roku_tv', 'on') }}

# ----------------------------------------------------------
# ----------------------------------------------------------

automation:
  # ----------------------------------------------------------
  - id: turn_on_family_room_lights_on_motion
    alias: Turn ON family room lights when motion detected
    trigger:
      - platform: state
        entity_id: binary_sensor.family_room_occupancy
        from: 'off'
        to: 'on'
    condition:
      # make sure that the TV is OFF
      - condition: state
        entity_id: remote.58_hisense_roku_tv
        state: 'off'
      - condition: state
        entity_id: switch.family_room_main_lights
        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.family_room_main_lights
#        data:
#          brightness_pct: "{{ states('input_number.mode') | int }}"
    mode: single
  # ----------------------------------------------------------
  - id: turn_off_family_room_lights
    alias: Turn OFF Family Room Lights when NO motion
    trigger:
      - platform: state
        entity_id: binary_sensor.family_room_occupancy
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: "{{ states('input_number.light_timeout') | int }}"
          seconds: 0
    condition:
      - condition: state
        entity_id: binary_sensor.family_room_occupancy
        state: 'off'
      # make sure the light is not on
      - condition: state
        entity_id: switch.family_room_main_lights
        state: 'on'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
 #     - service: switch.turn_on
 #       entity_id: switch.family_room_main_lights
 #       data:
 #         brightness_pct: "{{ states('input_number.lights_regular_mode') | int }}"
      - service: switch.turn_off
        entity_id: switch.family_room_main_lights
    mode: single
