frontend:
  themes: !include_dir_merge_named ../../themes
# lovelace:
#   mode: storage

#   dashboards:
#     lovelace-minimalist:
#       mode: yaml
#       title: Minimalist
#       icon: mdi:script
#       show_in_sidebar: true
#       filename: lovelace-minimalist.yaml
