

input_number:
  lights_night_mode:
    name: Lights Night Mode
    initial: 15
    min: 5
    max: 20
  lights_regular_mode:
    name: Lights Regular Mode
    initial: 60
    min: 20
    max: 100
  light_timeout:
    name: Light Timeout
    unit_of_measurement: "m"
    initial: 5
    min: 1
    max: 10
  


  
