system_health:

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: processor_temperature
      - type: memory_free
      - type: disk_use_percent
        arg: /
      - type: disk_use
      - type: disk_free

input_boolean:
  test_mode:
    name: Test Mode
    icon: mdi:code-array

fastdotcom:
  scan_interval:
      minutes: 5