binary_sensor:
  - platform: group
    name: "Basement Occupancy"
    device_class: motion
    entities:
      - binary_sensor.basement_seating_motion
      - binary_sensor.basement_pir
      - binary_sensor.kevin_is_working
      - binary_sensor.basement_tv
  - platform: group
    name: "Work Time"
    entities:
      - binary_sensor.workday_sensor
      - binary_sensor.worktime_sensor

# ----------------------------------------------------------
# ----------------------------------------------------------

# device_id: c8cce925ffa216107cb550b229508a8e 
# entity_id: light.basement_lights_light


input_boolean:
  disable_basement_motion_automation:
    name: Disable Basement Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false

template:
  - binary_sensor:
      - name: "Kevin is working"
        icon: mdi:laptop-account
        state: >
          {{ is_state('sensor.kevin_iphone_12_mini_ble', 'office') }}
      - name: "Basement TV"
        icon: mdi:television
        state: >
          {{ is_state('media_player.living_room', 'playing') }}

# ----------------------------------------------------------
# ----------------------------------------------------------

timer:
  basement_light_timer:
    duration: "00:05:00"
    restore: true
    icon: mdi:timer
    name: "Basement Light Timer"


# ----------------------------------------------------------
# ----------------------------------------------------------

script:

  turn_on_basement_lights:
    sequence:
      - condition: and
        conditions:
          - condition: state
            entity_id: light.basement_light
            state: 'off'
          - condition: time
            after: '07:00:00'
            before: '22:30:00'
      - service: light.turn_on
        entity_id: light.basement_light

  turn_off_basement_lights:
    sequence:
      - condition: state
        entity_id: light.basement_light
        state: 'on'
      - service: light.turn_off
        entity_id: light.basement_light


# ----------------------------------------------------------
# ----------------------------------------------------------

automation:

  - id: 'basement_automatic_lights'
    alias: 'Basement Automatic Lights'
    description: ''
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.basement_light_timer
      id: Basement Light Timer Finished
    - platform: state
      entity_id:
      - binary_sensor.basement_occupancy
      from: 'on'
      to: 'off'
      id: Basement Occupancy Cleared
    - platform: state
      entity_id:
      - binary_sensor.basement_occupancy
      from: 'off'
      to: 'on'
      id: Basement Occupancy Detected
    condition:
      - condition: state
        entity_id: input_boolean.disable_basement_motion_automation
        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_automations
        state: 'off'
      - condition: state
        entity_id: binary_sensor.work_time
        state: 'off'
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: Basement Occupancy Cleared
        sequence:
        - service: timer.start
          target:
            entity_id: timer.basement_light_timer
      - conditions:
        - condition: trigger
          id: Basement Occupancy Detected
        sequence:
        - service: timer.cancel
          data: {}
          target:
            entity_id: timer.basement_light_timer
        - service: script.turn_on_basement_lights
      - conditions:
        - condition: trigger
          id: Basement Light Timer Finished
        sequence:
        - service: script.turn_off_basement_lights
    mode: single