
automation:
  - id: 'turn_on_christmas_tree'
    alias: Turn ON Christmas Tree
    initial_state: true
    trigger:
      - platform: time
        at: "17:00:00"
    condition:
      - condition: state
        entity_id: switch.christmas_tree
        state: 'off'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_automations
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.christmas_tree
  - id: 'turn_of_christmas_tree'
    alias: Turn OFF Christmas Tree
    initial_state: true
    trigger:
      - platform: time
        at: "23:00:00"
    condition:
      - condition: state
        entity_id: switch.christmas_tree
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.christmas_tree
