input_boolean:
  school_today:
    name: School Today
    icon: mdi:bus-school

input_datetime:
  school_first_day:
    name: First Day of School
    has_date: true
    has_time: false
  school_last_day:
    name: Last Day of School
    has_date: true
    has_time: false

sensor:
  - platform: template
    sensors:
      school_start_days2go:
        value_template: "{{ ((state_attr('input_datetime.school_first_day', 'timestamp')-as_timestamp(now())) | int /60/1440) | round(0) }}"
        unit_of_measurement: 'Days'
      school_end_days2go:
        value_template: "{{ ((state_attr('input_datetime.school_last_day', 'timestamp')-as_timestamp(now())) | int /60/1440) | round(0) }}"
        unit_of_measurement: 'Days'
      # vacation_days2go:
      #   value_template: >
      #     {% if state_attr('calendar.vacation', 'start_time') %}
      #       {{ ((as_timestamp(strptime(state_attr('calendar.vacation', 'start_time'), '%Y-%m-%d'))-as_timestamp(now())) | int /60/1440) | round(0) }}
      #     {% else %}
      #       999
      #     {% endif %}
      #   unit_of_measurement: 'Days'
  - platform: rest
    resource: https://raw.githubusercontent.com/jkevinburton/homeassistant-config/main/config/packages/json_data/school.json
    name: School Lunch
    scan_interval: 14400
    value_template: >
      {% set today = now().month  ~ '/' ~ now().day  %}
      {% set lunch =  value_json.MENU.static[ today ] %}
      {%- if lunch %}
        {{ lunch  }}
      {% else %}
        Nothing
      {%- endif %}

automation:
  - id: refresh_special_event_sensors
    alias: Refresh special event sensors
    initial_state: true
    trigger:
      - platform: time
        at: '00:00:01'
      - platform: homeassistant
        event: start
    action:
      - service: python_script.special_events
        data:
          name: Charles
          type: birthday
          date: !secret charles_bday
      - service: python_script.special_events
        data:
          name: Denver
          type: birthday
          date: !secret denver_bday
      - service: python_script.special_events
        data:
          name: Keaton
          type: birthday
          date: !secret keaton_bday
      - service: python_script.special_events
        data:
          name: Kevin
          type: birthday
          date: !secret kevin_bday
      - service: python_script.special_events
        data:
          name: Tamara
          type: birthday
          date: !secret tamara_bday
      - service: python_script.special_events
        data:
          name: Our wedding
          type: anniversary
          date: !secret wed_anniversary