binary_sensor:
  - platform: group
    name: "Family Room Occupancy"
    device_class: motion
    entities:
      - binary_sensor.family_room_p1_motion
      - binary_sensor.family_room_secondary_pir
      - binary_sensor.theatre_mode

# ----------------------------------------------------------
# ----------------------------------------------------------

input_boolean:
  disable_family_room_motion_automation:
    name: Disable Family Room Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false

# ----------------------------------------------------------
# ----------------------------------------------------------

group:
  family_room_reading_lights:
    name: Reading Lights
    icon: mdi:track-light
    entities:
      - light.reading_lights_left
      - light.reading_lights_right

template:
  - binary_sensor:
      - name: "Theatre Mode"
        icon: mdi:television
        state: >
          {{ is_state('remote.58_hisense_roku_tv', 'on') }}

# ----------------------------------------------------------
# ----------------------------------------------------------

timer:
  family_room_light_timer:
    duration: "00:02:00"
    restore: true
    icon: mdi:timer
    name: "Family Room Light Timer"

# ----------------------------------------------------------
# ----------------------------------------------------------

automation:

  - id: 'family_room_automatic_lights'
    alias: 'Family Room Auotmatic Lights'
    description: ''
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.family_room_light_timer
      id: Family Room Light Timer Finished
    - platform: state
      entity_id:
      - binary_sensor.family_room_occupancy
      from: 'on'
      to: 'off'
      id: Family Room Occupancy Cleared
    - platform: state
      entity_id:
      - binary_sensor.family_room_occupancy
      from: 'off'
      to: 'on'
      id: Family Room Occupancy Detected
    condition: 
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_automations
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_family_room_motion_automation
        state: 'off'
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: Family Room Occupancy Cleared
        sequence:
        - service: timer.start
          target:
            entity_id: timer.family_room_light_timer
      - conditions:
        - condition: trigger
          id: Family Room Occupancy Detected
        sequence:
        - service: timer.cancel
          data: {}
          target:
            entity_id: timer.family_room_light_timer
        - type: turn_on
          device_id: cc1d59c6ebdeb959b70242cb0b81fd25
          entity_id: switch.family_room_main_lights
          domain: switch
      - conditions:
        - condition: trigger
          id: Family Room Light Timer Finished
        # endure that we haven't disabled the automation for any reason
        - condition: state
          entity_id: input_boolean.disable_family_room_motion_automation
          state: 'off'
        # ensure that the lights were on before trying to turn them off
        - condition: state
          entity_id: switch.family_room_main_lights
          state: 'on'
        sequence:
        - type: turn_off
          device_id: cc1d59c6ebdeb959b70242cb0b81fd25
          entity_id: switch.family_room_main_lights
          domain: switch
    mode: single