binary_sensor:
  - platform: group
    name: "Family Room Occupancy"
    device_class: motion
    entities:
      - binary_sensor.family_room_p1_motion
      - binary_sensor.family_room_secondary_pir
      - binary_sensor.theatre_mode

# ----------------------------------------------------------
# ----------------------------------------------------------

input_boolean:
  disable_family_room_motion_automation:
    name: Disable Family Room Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false

# ----------------------------------------------------------
# ----------------------------------------------------------

group:

  family_room_reading_lights:
    name: Reading Lights
    icon: mdi:track-light
    entities:
      - light.reading_lights_left
      - light.reading_lights_right

# ----------------------------------------------------------
# ----------------------------------------------------------

template:
  - binary_sensor:
      - name: "Theatre Mode"
        icon: mdi:television
        state: >
          {{ is_state('remote.58_hisense_roku_tv', 'on') }}

# ----------------------------------------------------------
# ----------------------------------------------------------

timer:
  family_room_light_timer:
    duration: "00:02:00"
    restore: true
    icon: mdi:timer
    name: "Family Room Light Timer"

# ----------------------------------------------------------
# ----------------------------------------------------------

script:

  turn_on_family_room_lights:
    sequence:
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.pot_lights
            state: 'off'
          - condition: time
            after: '07:30:00'
            before: '22:30:00'
          - condition: numeric_state
            entity_id: sensor.family_room_p1_motion_illuminance
            below: 100
      - service: switch.turn_on
        entity_id: switch.pot_lights

  turn_off_family_room_lights:
    sequence:
      - condition: state
        entity_id: switch.pot_lights
        state: 'on'
      - service: switch.turn_off
        entity_id: switch.pot_lights

# ----------------------------------------------------------
# ----------------------------------------------------------

automation:

  - id: 'family_room_automatic_lights'
    alias: 'Family Room Auotmatic Lights'
    description: ''
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.family_room_light_timer
      id: Family Room Light Timer Finished
    - platform: state
      entity_id:
      - binary_sensor.family_room_occupancy
      from: 'on'
      to: 'off'
      id: Family Room Occupancy Cleared
    - platform: state
      entity_id:
      - binary_sensor.family_room_occupancy
      from: 'off'
      to: 'on'
      id: Family Room Occupancy Detected
    condition: 
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_automations
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_family_room_motion_automation
        state: 'off'
    action:
    - choose:
      - conditions:
        - condition: trigger
          id: Family Room Occupancy Cleared
        sequence:
        - service: timer.start
          target:
            entity_id: timer.family_room_light_timer
      - conditions:
        - condition: trigger
          id: Family Room Occupancy Detected
        sequence:
        - service: timer.cancel
          data: {}
          target:
            entity_id: timer.family_room_light_timer
        - service: script.turn_on_family_room_lights
      - conditions:
        - condition: trigger
          id: Family Room Light Timer Finished
        sequence:
        - service: script.turn_off_family_room_lights
    mode: single