###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   02/19/2019
#   @package        :   Holidays
#   @description    :   Holiday Specific.
#
#   I'm not sure where I got this, but it leverages a python script: https://github.com/thejeffreystone/home-assistant-configuration/blob/master/python_scripts/special_events.py
#
#   To create a sensor just create an automation to fire around midnight.
#
#   automation:
#   - id: refresh_holioday_sensors
#     alias: Refresh Holiday sensors
#     initial_state: true
#     trigger:
#     - platform: time
#       at: '00:00:07'
#     - platform: homeassistant
#       event: start
#     action:
#     - service: python_script.special_events
#       data:
#         name: Christmas
#         type: holiday
#         date: 25/12/2001
#
#   Where Name equals the name of the event, type is the type of event, and date is the date in DD/MM/YYYY format
#
#   Year only matters if your want to take advantage fo the years attribute which will tell you have many years since the event. Useful
#   with birthdays and anniversaries.
#
#   I use the Following types:
#   birthday
#   anniversary
#   holiday
#   trip
#
#   The type will be used in the name of the sensor it creates. For example:
#   sensor.trip_camping
#   sensor.birthday_jeff
#   sensor.holiday_christmas
#
#   The state of the sensor will be the days until the event. For birthdays and anniversaries it will never be more than 365.
#   For example {{ states.sensor.birthday_jeff.state }} will be the number of days until my next birthday.
#   And {{ states.sensor.birthday_jeff.attributes.years }} will be my age, or the number of years since my birth (if you put the real year in)
#   For events with a year in the future, the state will be number of days to that exact moment in time.
#
###############################################################################

sensor:
  # Countdown Sensor using Wolfram Alpha Natural language queries

  - platform: rest
    name: Halloween Countdown
    resource: !secret wa_halloween
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Christmas Countdown
    resource: !secret wa_christmas
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Mothers Day Countdown
    resource: !secret wa_mothersday
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

script:
  manual_refresh_special_events:
    sequence:
      - service: python_script.special_events
        data:
          name: Charles
          type: birthday
          date: !secret charles_bday
      - service: python_script.special_events
        data:
          name: Denver
          type: birthday
          date: !secret denver_bday
      - service: python_script.special_events
        data:
          name: Keaton
          type: birthday
          date: !secret keaton_bday
      - service: python_script.special_events
        data:
          name: Kevin
          type: birthday
          date: !secret kevin_bday
      - service: python_script.special_events
        data:
          name: Tamara
          type: birthday
          date: !secret tamara_bday
      - service: python_script.special_events
        data:
          name: Our wedding
          type: anniversary
          date: !secret wed_anniversary
      # - service: python_script.special_events
      #   data:
      #     name: Kitchen Reno Day
      #     type: event
      #     date: !secret kitchen_reno

automation:
  - id: refresh_special_event_sensors
    alias: Refresh special event sensors
    initial_state: true
    trigger:
      - platform: time
        at: "00:00:01"
      - platform: homeassistant
        event: start
    action:
      - service: script.manual_refresh_special_events
