input_boolean:
  disable_automations:
    name: Disable Automations
    icon: mdi:arrow-decision-auto
    initial: false
  guest_mode:
    name: Guest Mode
    icon: mdi:account-group
    initial: false