binary_sensor:
  - platform: group
    name: "Kitchen Occupancy"
    device_class: motion
    entities:
      - binary_sensor.kitchen_p1_motion
      - binary_sensor.front_door_contact_sensor
      
  
# ----------------------------------------------------------
# ----------------------------------------------------------

input_boolean:
  disable_kitchen_motion_automation:
    name: Disable Kitchen Motion Automation
    icon: mdi:arrow-decision-auto
    initial: false
  

# ----------------------------------------------------------
# ----------------------------------------------------------

template:
  - sensor:
      - name: Kitchen Light Brightness
        icon: mdi:lightbulb-on-outline
        state: >
          {{ state_attr('light.mj_kitchen_switch', 'brightness') }}

# ----------------------------------------------------------
# ----------------------------------------------------------

timer:
  kitchen_light_timer:
    duration: "00:02:00"
    restore: true
    icon: mdi:timer
    name: "Kitchen Light Timer"
  

# ----------------------------------------------------------
# ----------------------------------------------------------

script:

  turn_on_kitchen_lights:
    sequence:
      - condition: state
        entity_id: light.mj_kitchen_switch
        state: 'off'
      - condition: time
        after: '06:00:00'
        before: '22:30:00'
      - service: light.turn_on
        entity_id: light.mj_kitchen_switch
        data:
          brightness: 180


  turn_off_kitchen_lights:
    sequence:
      - condition: state
        entity_id: light.mj_kitchen_switch
        state: 'on'
      - service: light.turn_off
        entity_id: light.mj_kitchen_switch

  
# ----------------------------------------------------------
# ----------------------------------------------------------

automation:

  # Kitchen lights needed when dark and there is motion

  - id: 'kitchen_automatic_lights'
    alias: 'Kitchen Auotmatic Lights'
    description: ''
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_light_timer
      id: Kitchen Light Timer Finished
    - platform: state
      entity_id:
      - binary_sensor.kitchen_occupancy
      from: 'on'
      to: 'off'
      id: Kitchen Occupancy Cleared
    - platform: state
      entity_id:
      - binary_sensor.kitchen_p1_motion
      from: 'off'
      to: 'on'
      id: Kitchen Occupancy Detected
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_automations
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_kitchen_motion_automation
        state: 'off'
    action:
    - choose:
      
      # motion cleared, start the countdown to turn off the lights
      - conditions:
        - condition: trigger
          id: Kitchen Occupancy Cleared
        sequence:
        - service: timer.start
          target:
            entity_id: timer.kitchen_light_timer

      # motion detected, turn on the lights
      - conditions:
        - condition: trigger
          id: Kitchen Occupancy Detected
        sequence:
        - service: timer.cancel
          target:
            entity_id: timer.kitchen_light_timer
        - service: script.turn_on_kitchen_lights

      # timer finished, turn off the lights if someone didn't already do it.
      - conditions:
        - condition: trigger
          id: Kitchen Light Timer Finished
        sequence:
          - service: script.turn_off_kitchen_lights
    mode: single
