
automation:
  - id: test_aqara_button
    alias: Test Awara Button
    initial_state: true
    trigger:
      - type: remote_button_short_press
        subtype: remote_button_short_press
        device_id: 3716640de90dc69c60bbb7f030b8261f
        domain: zha
        platform: device
    condition: []
    action:
      - service: switch.toggle
        entity_id: switch.family_room_main_lights
  
