binary_sensor:
  - platform: workday
    country: CA
    province: "ON"
    workdays: [mon, tue, wed, thu, fri]

  - platform: tod
    name: "Night Time"
    after: sunset
    before: sunrise

  - platform: tod
    name: "Day Time"
    after: sunrise
    before: sunset

  - platform: tod
    name: "Morning"
    after: "06:00"
    before: "12:00"

  - platform: tod
    name: "Afternoon"
    after: "12:00"
    before: "17:00"

  - platform: tod
    name: "Evening"
    after: "17:00"
    before: "23:00"

  - platform: tod
    name: "Worktime Sensor"
    after: "10:00:00"
    before: "23:00:00"