homeassistant:
  name: Burton House on Gladstone
  unit_system: metric
  time_zone: !secret time_zone
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: !secret elevation
  # --
  external_url: !secret bh_base_url
  internal_url: http://10.107.1.107:8123
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
  # media_dirs:
  #   sounds: /media/sounds
  #   images: /media/images

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  # ssl_certificate: !secret ahsl_ssl_cert
  # ssl_key: !secret ahsl_ssl_key
  # use_x_forwarded_for: true
  # trusted_proxies: !secret proxy_ips
  # ip_ban_enabled: false
  # login_attempts_threshold: 5

ssdp:

zeroconf:

conversation:

system_health:

mobile_app:

person:

frontend:
  themes: !include_dir_merge_named themes

cloud:

# device_tracker:
#   - platform: 
#     consider_home: 300
#     interval_seconds: 60
#     only_macs: ""

discovery:

# updater:
#   include_used_components: true

sun:

python_script:

map:

group: !include groups.yaml

# --------------------------------------------
# Includes

alert: !include_dir_merge_named alerts
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
# light: !include lights.yaml
switch: !include switches.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
zone: !include zones.yaml

panel_iframe:
  vscode:
    title: "Visual Studio Code"
    icon: mdi:microsoft-visual-studio-code
    url: !secret codeserver_url
    require_admin: true
  esphome:
    title: "ESPHome"
    icon: mdi:script-text-key-outline
    url: !secret esphome_url
    require_admin: true