homeassistant:
  name: Burton House
  unit_system: metric
  time_zone: !secret time_zone
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: !secret elevation
  packages: !include_dir_named packages

python_script:
input_text:
input_number:

automation: !include automations.yaml
