homeassistant:
  name: Burton House on Gladstone
  unit_system: metric
  time_zone: !secret time_zone
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: !secret elevation
  packages: !include_dir_named components/packages

python_script:
input_text:
input_number:

# automation: !include automations.yaml #!include_dir_named components/automation

panel_iframe:
  vscode:
    title: "Visual Studio Code"
    icon: mdi:microsoft-visual-studio-code
    url: !secret codeserver_url
    require_admin: true
  esphome:
    title: "ESPHome"
    icon: mdi:script-text-key-outline
    url: !secret esphome_url
    require_admin: true